#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings                            
yabai -m config mouse_follows_focus          off
# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse          autoraise            
yabai -m config window_origin_display        default        
yabai -m config window_placement             first_child   
yabai -m config window_topmost               off            
yabai -m config window_shadow                off           
yabai -m config window_opacity               off            
yabai -m config window_opacity_duration      0.0            
yabai -m config active_window_opacity        1.0            
yabai -m config normal_window_opacity        0.90           
yabai -m config window_border                on            
yabai -m config window_border_width          1             
yabai -m config active_window_border_color   0xff1ba1ff     
yabai -m config normal_window_border_color   0xff555555     
yabai -m config insert_feedback_color        0xffd75f5f     
yabai -m config split_ratio                  0.50           
yabai -m config auto_balance                 off            
yabai -m config mouse_modifier               fn             
yabai -m config mouse_action1                move           
yabai -m config mouse_action2                resize         
yabai -m config mouse_drop_action            swap           
yabai -m config top_padding                  10             
yabai -m config bottom_padding               10             
yabai -m config left_padding                 10             
yabai -m config right_padding                10             
yabai -m config window_gap                   10             
yabai -m config layout                       bsp

#
# setup spaces
#
# if you change the amount of spaces you want, you'll need to change the 9 and 10
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 9)'); do
  yabai -m space --destroy 10
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}


setup_space 1 notes
setup_space 2 web
setup_space 3 music
setup_space 4 workchat
setup_space 5 dev
setup_space 6 design
setup_space 7 audio
setup_space 8 video
setup_space 9 finder

# move some apps automatically to specific spaces
# I have decided to try only having Music set to a specific space as I want to trial moving windows around spaces more.
yabai -m rule --add app="^Music$" space=9
#yabai -m rule --add app="^Google Chrome$" space=^2
#yabai -m rule --add app="^Google Chrome Dev$" space=^2
#yabai -m rule --add app="^Firefox$" space=2
yabai -m rule --add app="^Notion$" space=8
#yabai -m rule --add app="^Spotify$" space=3
#yabai -m rule --add app="Photoshop" space=6
#yabai -m rule --add app="Illustrator" space=6
#yabai -m rule --add app="Premiere" space=8
#yabai -m rule --add app="After Effects" space=8
#yabai -m rule --add app="^Figma$" space=6
#yabai -m rule --add app="VSCodium" space=5
#yabai -m rule --add app="^Code$" space=5
#yabai -m rule --add app="^Emacs$" space=5
#yabai -m rule --add app="^Asana$" space=4
#yabai -m rule --add app="^Slack$" space=4
#yabai -m rule --add app="^Live$" space=7
#yabai -m rule --add app="^Logic Pro$" space=7
#yabai -m rule --add app="^Audacity$" space=7
#yabai -m rule --add app="Premiere" manage=on
#yabai -m rule --add app="After Effects" manage=on
#yabai -m rule --add app=Emacs manage=on
#yabai -m rule --add app="^Creative Cloud$" manage=off

echo "yabai configuration loaded.."
