#!/usr/bin/env sh

## hyper = ctrl + alt + cmd + shift
# you can actually just use the word 'hyper' unlike semihyper.
## semihyper = ctrl + alt + cmd

# focus window - normal way
# hyper - h : yabai -m window --focus west
# hyper - k : yabai -m window --focus north
# hyper - j : yabai -m window --focus south
# hyper - l : yabai -m window --focus east

# move window to space 'x' - not working
# ctrl + alt + cmd + shift - 1 : yabai -m window --space 1
# ctrl + alt + cmd + shift - 2 : yabai -m window --space 2
# ctrl + alt + cmd + shift - 3 : yabai -m window --space 3
# ctrl + alt + cmd + shift - 4 : yabai -m window --space 4
# ctrl + alt + cmd + shift - 5 : yabai -m window --space 5
# ctrl + alt + cmd + shift - 6 : yabai -m window --space 6
# ctrl + alt + cmd + shift - 7 : yabai -m window --space 7
# ctrl + alt + cmd + shift - 8 : yabai -m window --space 8
# ctrl + alt + cmd + shift - 9 : yabai -m window --space 9
# ctrl + alt + cmd + shift - 10 : yabai -m window --space 10

## tilde to shift between normal mac noob mode and full yabai mode.
ctrl + alt + cmd - 0x35 : [[ $(yabai -m config layout) = "bsp" ]] && \
    (yabai -m config layout float; \
    yabai -m config window_border off; \
    yabai -m config window_shadow on; \
    yabai -m config focus_follows_mouse off) || \
    (yabai -m config layout bsp; \
    yabai -m config window_border on; \
    yabai -m config window_shadow off; \
    yabai -m config focus_follows_mouse autoraise)

# cycle all windows on space backwards by coordinate
ctrl + alt + cmd - k : yabai -m window --focus "$( \
    yabai -m query --windows --space \
        | jq -re "sort_by(.frame) | map(.id) | nth(1 + index($( \
            yabai -m query --windows --window | jq '.id'))) // first")"
ctrl + alt + cmd - j : yabai -m window --focus "$( \
    yabai -m query --windows --space \
        | jq -re "sort_by(.frame) | reverse | map(.id) | nth(1 + index($( \
            yabai -m query --windows --window | jq '.id'))) // first")"

ctrl + alt + cmd - return : /Applications/Alacritty.app/Contents/MacOS/alacritty
ctrl + alt + cmd - 0x1B : [[ $(yabai -m config layout) = "bsp" ]] && \
    yabai -m config layout float || \
    yabai -m config layout bsp

## swap window set up as faux Master Window like dwm
ctrl + alt + cmd - y : yabai -m window --swap west && yabai -m window --swap north && yabai -m window --swap west && yabai -m window --swap north
# shift + alt - j : yabai -m window --swap south
# shift + alt - k : yabai -m window --swap north
ctrl + alt + cmd - 0x21 : yabai -m window --swap east # 0x21 is the "[" key

## send window to monitor and follow focus
# hyper - u : /Users/jesseskelton/CustomScripts/SwitchSpaces/moveWindowLeftAndFollowFocus.sh
# hyper - p : /Users/jesseskelton/CustomScripts/SwitchSpaces/moveWindowRightAndFollowFocus.sh

## focus display
# ctrl + cmd - 1 : yabai -m window --display 1 yabai -m display --focus 1
# ctrl + cmd - 2 : yabai -m window --display 2 yabai -m display --focus 2
# ctrl + cmd - 3 : yabai -m window --display 3 yabai -m display --focus 3

## increase window size
ctrl + alt + cmd - h : yabai -m window --resize left:-20:0
#shift + alt - s : yabai -m window --resize bottom:0:20
# hyper - w : yabai -m window --resize top:0:-20
ctrl + alt + cmd - l : yabai -m window --resize right:20:0

## decrease window size
# shift + cmd - a : yabai -m window --resize left:20:0
#shift + cmd - s : yabai -m window --resize bottom:0:-20
#shift + cmd - w : yabai -m window --resize top:0:20
#shift + cmd - d : yabai -m window --resize right:-20:0

## rotate tree 90
ctrl + alt + cmd + shift - r : yabai -m space --rotate 90

## flip the tree vertically
ctrl + alt + cmd - 0x2B : yabai -m space --mirror y-axis
# mirror tree y-axis
#alt - y : yabai -m space --mirror y-axis
## mirror tree x-axis
#alt - x : yabai -m space --mirror x-axis

#Move active window to next space on current display
# shift + lalt + lcmd + ctrl + ralt - 1 : yabai -m query --spaces --space | jq -re ".index" | xargs -I {} bash -c "if [[ '{}' = '1' ]]; then yabai -m window --space 2; elif [[ '{}' = '2' ]]; then yabai -m window --space 1; fi"
# shift + lalt + lcmd + ctrl + ralt - 2 : yabai -m query --spaces --space | jq -re ".index" | xargs -I {} bash -c "if [[ '{}' = '3' ]]; then yabai -m window --space 4; elif [[ '{}' = '4' ]]; then yabai -m window --space 3; fi"
# shift + lalt + lcmd + ctrl + ralt - 3 : yabai -m query --spaces --space | jq -re ".index" | xargs -I {} bash -c "if [[ '{}' = '5' ]]; then yabai -m window --space 6; elif [[ '{}' = '6' ]]; then yabai -m window --space 5; fi"

# show next space per display
#hyper - 1 : /Users/jesseskelton/CustomScripts/SwitchSpaces/switchAndFocus.sh 1
#hyper - 2 : /Users/jesseskelton/CustomScripts/SwitchSpaces/switchAndFocus.sh 2
#hyper - 3 : /Users/jesseskelton/CustomScripts/SwitchSpaces/switchAndFocus.sh 3
# ctrl + alt + cmd + lshift - 1 : /Users/jesseskelton/CustomScripts/SwitchSpaces/switchAndFocusSIP.sh 1
# ctrl + alt + cmd + lshift - 2 : /Users/jesseskelton/CustomScripts/SwitchSpaces/switchAndFocusSIP.sh 2
# ctrl + alt + cmd + lshift - 3 : /Users/jesseskelton/CustomScripts/SwitchSpaces/switchAndFocusSIP.sh 3

## toggle window fullscreen zoom
ctrl + alt + cmd - f : yabai -m window --toggle zoom-fullscreen


################################################################
############################# UNUSED ###########################
################################################################

## float / unfloat window and center on screen
#alt - t : yabai -m window --toggle float;\
#yabai -m window --grid 4:4:1:1:2:2 ## toggle sticky alt - s : yabai -m window --toggle sticky ## toggle sticky, float and resize to picture-in-picture size alt - p : yabai -m window --toggle sticky;\ yabai -m window --grid 5:5:4:0:1:1 ## change layout of desktop ctrl + alt - a : yabai -m space --layout bsp ctrl + alt - d : yabai -m space --layout float

## toggle window split type
#alt - e : yabai -m window --toggle split

## toggle window border
## if the first command in double brackets is successfull then do whats after && and if not do whats after ||
## So if it's on turn it off and if it's not then turn it on.
ctrl + alt + cmd - b : [[ $(yabai -m config window_border) = "on" ]] && \
    yabai -m config window_border off || \
    yabai -m config window_border on
# yabai -m config window_border off
# yabai -m window --toggle border

## create desktop, move window and follow focus
#shift + cmd - n : yabai -m space --create && \
#index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')" && \
#yabai -m window --space "${index}" && \
#yabai -m space --focus "${index}"

## create desktop and follow focus
ctrl + alt + cmd - n : yabai -m space --create
# hyper - n : yabai -m space --create && \
# index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')" && \
# yabai -m space --focus "${index}"

## destroy desktop
ctrl + alt + cmd + shift - w : yabai -m space --destroy

## fast focus desktop
ctrl + alt + cmd - x : yabai -m space --focus last
ctrl + alt + cmd - z : yabai -m space --focus prev
ctrl + alt + cmd - c : yabai -m space --focus next
ctrl + alt + cmd - 1 : yabai -m space --focus 1
ctrl + alt + cmd - 2 : yabai -m space --focus 2
ctrl + alt + cmd - 3 : yabai -m space --focus 3
ctrl + alt + cmd - 4 : yabai -m space --focus 4
ctrl + alt + cmd - q : yabai -m space --focus 5
ctrl + alt + cmd - w : yabai -m space --focus 6
ctrl + alt + cmd - e : yabai -m space --focus 7
ctrl + alt + cmd - r : yabai -m space --focus 8
ctrl + alt + cmd - 0x32 : yabai -m space --focus 9
# ctrl + alt + cmd - 9 : yabai -m space --focus 9
# hyper - 0 : yabai -m space --focus 10

## move window
# hyper - a : yabai -m window --move rel:-20:0
# hyper - s : yabai -m window --move rel:0:20
# hyper - w : yabai -m window --move rel:0:-20
# hyper - d : yabai -m window --move rel:20:0

## Swap window
# hyper - y : yabai -m window --warp west
# hyper - j : yabai -m window --warp south
# hyper - k : yabai -m window --warp north
# hyper - 0x21 : yabai -m window --warp east # "[" key

## focus monitor
#ctrl + alt - x  : yabai -m display --focus last
#ctrl + alt - z  : yabai -m display --focus prev || yabai -m display --focus last
#ctrl + alt - c  : yabai -m display --focus next || yabai -m display --focus first
#ctrl + alt - 1  : yabai -m display --focus 1
#ctrl + alt - 2  : yabai -m display --focus 2
#ctrl + alt - 3  : yabai -m display --focus 3

ctrl + alt + cmd - m : [[ $(yabai -m config focus_follows_mouse) = "autoraise" ]] && \
    yabai -m config focus_follows_mouse off || \
    yabai -m config focus_follows_mouse autoraise
